# Generated by Django 4.1.1 on 2022-10-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_comments_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
